import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html lang="en">
      <Head />
      {/* <script src="http://localhost:8097"></script> */}
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>Julio Camargo</title>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}

 
