import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'


export default function Home() {
  return (
    <>
      <Head>
        <title>Julio Camargo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.mainH1}><span>Hi,</span>My name is Julio,a Web Developer based in London </h1>
        <h2 className={styles.mainH1}>This website will be out soon</h2>
      </main>
    </>
  )
}
